# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: mahr@wisc.edu
    on_failure: mahr@wisc.edu

r_github_packages:
  - jimhester/covr
  - Rexamine/stringi

after_success:
  - Rscript -e 'library(covr);coveralls()'
