# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
warnings_are_errors: true
sudo: required

env:
  global:
    - CRAN: http://cran.rstudio.com
    - GH_REF: tjmahr/rprime
    - secure: "RvEPhfZErOAtFJAaSwgHgMrHYaUVVL1RiISwXH498hw2o/rBnCrg24WVN1oLOQZZQkcYdW+EDfCl6J/OhT7hRKSPCD8Yz+Rhj1zEHrQXSNAi8c3JETUwJirZUe2H2bkC0YUfMQ3sQaDipX/uIeXmk0BVUkETgeWb1UBzG8wNg28="

notifications:
  email:
    on_success: mahr@wisc.edu
    on_failure: mahr@wisc.edu

r_github_packages:
  - jimhester/covr
  - Rexamine/stringi
  - hadley/staticdocs

r_binary_packages:
  - roxygen2

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - mkdir -p ./inst/staticdocs
  - Rscript -e 'staticdocs::build_site()'
  - ./deploy-pages.sh
