# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com
   - GH_REF: tjmahr/rprime
   - secure: "PIoZe3t59W1CUuUNxMlA/VyAoRfI4C0JtnH/7I53ksALb83Y0rGnfqpFlN8Xgro9rLPv/Mz1gY373fWRCb1ugb5A7x84uXjJQ8Ht45rwPgwCagN/kbYsA/EZiRSksfhUGhzMH6gO/razkZURavakr6ClWegHcxVJ05u1bNf71Ac="

notifications:
  email:
    on_success: mahr@wisc.edu
    on_failure: mahr@wisc.edu

r_github_packages:
  - jimhester/covr
  - Rexamine/stringi
  - hadley/staticdocs

r_binary_packages:
  - roxygen2

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - mkdir -p ./inst/staticdocs
  - Rscript -e 'staticdocs::build_site()'
  - ./deploy-pages.sh
